### ISSUE TITLE
请教您一个问题，我编译您的代码的时候出现这个

### ISSUE THREAD

**Issue by peopleel** [crossfw/Xray-API-documents#2]
[root@96 gofile]# go build structures.go 
structures.go:4:2: no required module provides package github.com/xtls/xray-core/app/log/command: working directory is not part of a module
structures.go:5:2: no required module provides package github.com/xtls/xray-core/app/proxyman/command: working directory is not part of a module
structures.go:6:2: no required module provides package github.com/xtls/xray-core/app/router/command: working directory is not part of a module
structures.go:7:2: no required module provides package github.com/xtls/xray-core/app/stats/command: working directory is not part of a module
structures.go:8:2: no required module provides package google.golang.org/grpc: working directory is not part of a module
对于go语言，我不懂，今天刚安装成功，用它编译您的代码出现这个问题。我知道可能是因为包的原因。但我不知道是不是要把XTLS等需要的包下载下来或者放到哪里，很抱歉问了这么个小白的问题，希望得到您的解答，谢谢！

**Comment by peopleel** [comment]
> [root@96 gofile]# go build structures.go
> structures.go:4:2: no required module provides package github.com/xtls/xray-core/app/log/command: working directory is not part of a module
> structures.go:5:2: no required module provides package github.com/xtls/xray-core/app/proxyman/command: working directory is not part of a module
> structures.go:6:2: no required module provides package github.com/xtls/xray-core/app/router/command: working directory is not part of a module
> structures.go:7:2: no required module provides package github.com/xtls/xray-core/app/stats/command: working directory is not part of a module
> structures.go:8:2: no required module provides package google.golang.org/grpc: working directory is not part of a module
对于go语言，我不懂，今天刚安装成功，用它编译您的代码出现这个问题。我知道可能是因为包的原因。但我不知道是不是要把XTLS等需要的包下载下来或者放到哪里，很抱歉问题这么一个小白的问题，希望得到您的解答，谢谢

**Comment by crossfw** [comment]
这只是样例，没有main包并不能编译运行，可以运行Test程序测试。
